=== hmdang2206/Bt_Xml/DTD/Bt5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT html (head+,body+)>
<!ELEMENT head (title+,link+,script*)>
<!ELEMENT body ((div|span)+,script*)>
<!ELEMENT div ((p|a|table|div)+)>
<!ELEMENT span ((p|a|table|span)+)>
<!ELEMENT table (tr+)>
<!ELEMENT tr (td+)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT a (#PCDATA)>
<!ELEMENT td (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link href CDATA #REQUIRED>
<!ELEMENT script (#PCDATA)>
<!ATTLIST script src CDATA #REQUIRED>
<!ATTLIST a src CDATA #REQUIRED>

=== hmdang2206/Bt_Xml/DTD/Bt5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<!DOCTYPE html SYSTEM 'Bt5.dtd'>


<html>
    <head>
        <title></title>
        <link href=""></link>
        <script src=""></script>
    </head>
    <body>
        <div>
            <table>
                <tr>
                    <td></td>
                </tr>
            </table>
            <p>
            </p>
            <a src=""></a>
            <p></p>
        </div>
        <span>
            <p></p>
        </span>
    </body>
</html>
